apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  commonName: kosamara-notebooks.web.cern.ch
  # Use dnsNames if your LoadBalancer issues a hostname (eg on AWS)
  dnsNames:
  - kosamara-notebooks.web.cern.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: istio-ingressgateway-certs
